### ISSUE TITLE
Feature: Automatically add .gitignore into a storage directory folder

### ISSUE THREAD

**Issue by nathanjmcdougall** [ben-denham/labtech#15]
I think a .gitignore file with `*` by default would a nice addition to a storage directory, if the storage directory does not already exist and is created by labtech.

**Comment by ben-denham** [comment]
Good idea, I've added this in abec60e, but I've made it more aggressive in that it will ensure the gitignore always exists, and replaces any existing gitignore. If a user wants to manage it themselves, they can set `with_gitignore=False`.
