### ISSUE TITLE
Feature: Allow `labtech.Lab` to accept a `pathlib.Path` type in `storage` argument

### ISSUE THREAD

**Issue by nathanjmcdougall** [ben-denham/labtech#2]
I prefer to pass around `pathlib.Path` objects for all paths, at the moment, I am forced to coerce using `.asposix()`, it would be a nice feature if `labtech` provided this conversion automatically.

**Comment by ben-denham** [comment]
Good point @nathanjmcdougall, this is fixed by https://github.com/ben-denham/labtech/commit/50c5e76d183e0dd43e0cb0e5d745a0d6647170c1 and will be included in the next release.
