### ISSUE TITLE
Font in SVG logo renders inconsistently

### ISSUE THREAD

**Issue by nathanjmcdougall** [ben-denham/labtech#22]
This is what I see on Microsoft Edge browser on my machine:

![image](https://github.com/ben-denham/labtech/assets/18602289/fff82772-52dc-4063-a746-405d4e291380)

Whereas I believe this is the intended appearance:

![image](https://github.com/ben-denham/labtech/assets/18602289/652c06f1-87e6-47e6-a561-9ab66bc10ed1)

I suggest that you export the SVG with vectorized fonts.

**Comment by ben-denham** [comment]
Thanks for catching that, I've just pushed a fix in 867b570.
