### ISSUE TITLE
Better error message when user forgets `@labtech.task` decorator

### ISSUE THREAD

**Issue by nathanjmcdougall** [ben-denham/labtech#8]
I was finding that when I defined task classes, I sometimes forgot the `@labtech.task `decorator.

I got a cryptic error:
`AttributeError: type object 'MyTask' has no attribute '_lt'`

Whereas I think this should be explicitly handled and a more informative error given,

**Comment by ben-denham** [comment]
Good catch, we should probably make `Lab.run_tasks` (and other methods) raise a `LabError` formatted with the offending object's repr if `is_task` (or `is_task_type` for types) returns false for any argument.
